DOMAIN = "naim_streamer"
DEFAULT_NAME = "Naim Streamer"
SERVICE_SEND_COMMAND = "send_command"
CONF_BROADLINK = "broadlink_entity"
CONF_RENDERING_CONTROL_URL = "rendering_control_url"
CONF_AV_TRANSPORT_URL = "av_transport_url"
CONF_CONNECTION_MANAGER_URL = "connection_manager_url"

BROADLINK_COMMANDS = {
    "disp": "JgAsADkgGj04Pjc+OB8cIBo8GiAcIBsAC2U3IBs+Nz06OzkgGiAbPRsfGyAbAA0FAAAAAAAAAAAAAAAA",
    "one": "JgAwABofGyAcHzg8OD05IBogGiAbIBo9GQALaBoeHh4cHzo7Nz45HxogGyAaHxs/GgANBQAAAAAAAAAA",
    "two": "JgAsABshOTs4PTo7OR4cIRgiGj04AAZ4CgAFARsgNzo8PTc9OSEZIBsgGj04AA0FAAAAAAAAAAAAAAAA",
    "three": "JgAwAB0fGSIZHzo8OT04HxsgGh8aPxwgGgALZBwfGiAcHzg9OD03IRsfGyAaPRkiGgANBQAAAAAAAAAA",
    "four": "JgAoABsgOTw5PDg+OB8cIBo9NyAbAAuDGyA3Pjg+Nj05IBogGj83IBoADQU=",
    "five": "JgAsABsgHB4bIDc9OT43IBogGz43PhwAC2McHxsfGyA4PDk+NyAbIBo9OD0bAA0FAAAAAAAAAAAAAAAA",
    "six": "JgAsABwfHCAaHzk8OT05HxsfGzwcIDcAC4MbHxohHB83PTg+OB8bIBs+Gh84AA0FAAAAAAAAAAAAAAAA",
    "seven": "JgAsABogNz83Pjc9OSAdHhs7GyAbIBsAC2UbHzg+Nz45OzkfGyAZPhshGiAaAA0FAAAAAAAAAAAAAAAA",
    "eight": "JgAwABsfGyAcHjg+Nz44Hxs9NyEbIBoAC4IcIBohGSA4PTg+NyAbPjkdHB8bAAc3BwANBQAAAAAAAAAA",
    "nine": "JgAoABogODw6Ozs7OCAaPTofGj0cAAtlGyA3Pjg9Nz42Iho+NyAaPR0ADQU=",
    "zero": "JgAwABwhGh8cHjw6Nz44IBogGx8bHxsgGwALgxofGyEbHjg9OD05IhkjFyAbIBkgGwANBQAAAAAAAAAA",
    "preset": "JgAoABohNzw6PDk8OR8aPRsgGx84AAuEGiA5PDg9OD44IBk+GyAaIDUADQU=",
    "store": "JgAWABwgGx4bITU+OD8ZIjc8OCEbPRsADQUAAA==",
    "vol+": "JgA0AAkACCgdHzg9NyAbIRkgHB8ZPjkfGiAbIBoAC4QdHTk9Nx8bIBohGx8bPzQjGR0eHxsADQUAAAAA",
    "vol-": "JgA4ABshGx8aITkeGh8cIBkjGD44HxsfGz4aAAtnGh8bIRkhNiEaIBwgFyMaPjcgGiEZPRwAAvoKAA0F",
    "mute": "JgAwABsgODw6HxogGx8bHxohGzwcIDY/GgALZhsgOTs4IRogGiAbIBofHDwcHzg+GgANBQAAAAAAAAAA",
    "ok": "JgAUADk8HCA4PTc+Nz45PBsgGx8bAA0FAAAAAA==",
    "up": "JgAoADchGz44PTc9OTw6HhsgGx8bAAuEOB8bPDg+OT04PDsdGyAaIBoADQU=",
    "down": "JgAoADc9HB84PTg9OD04IRsfGT4bAAtlOT0bITY+ODw5PTodGyAcPBwADQU=",
    "left": "JgAkADggHDs5PTg+OD04PDk9GwALZjcgGzw6PDg9OD43PTk9GwANBQAAAAA=",
    "right": "JgASADc/Gx83Pjg8OT05PBsfOQANBQAAAAAAAA==",
    "exit": "JgAoADofGT44Pjc7Ozw5IBo+GiEZAAtmOCAbPDo8OD43PjcgGzwgHB0ADQU=",
    "repeat": "JgAsABsgGiEaIDg9ODw5PBwgGiA4PRwAC2QbHxsgHB83PTk9Nj8bIRkgNz4cAA0FAAAAAAAAAAAAAAAA",
    "shuffle": "JgAsABsgNz05PDk8HCAbHxogOB8bIBsAC4MbIDc+Nz05PRshGh8bHzghGSAbAA0FAAAAAAAAAAAAAAAA",
    "setup": "JgAkADo7HCA3PTk8Ojs6OzofGgALgzk8HB84Pjc9Ojs5PDkfGwANBQAAAAA=",
    "info": "JgAsABoiODs5PTg9OR8bPRshGSAbHxwAC2QbHzk9Ojs4PTkfHDwcHxsfGx8cAA0FAAAAAAAAAAAAAAAA",
    "play": "JgAsABsgGyAaHzg9OT0aIBwhNj05OxwAC2UcHhweHR82Pjk8GyAbIDc+OD0bAA0FAAAAAAAAAAAAAAAA",
    "pause": "JgAsABsgGyAaHzg9OT0aIBwhNj05OxwAC2UcHhweHR82Pjk8GyAbIDc+OD0bAA0FAAAAAAAAAAAAAAAA",
    "previous": "JgAwABogGx8cHzg8NzohHzgfHB8aIBw7HAALZhogGh8cIDc+OTwaITcgGh8cIBw8GQANBQAAAAAAAAAA",
    "next": "JgAsABweOT03Pjc+GyA3IBsgGx8aHx0AC4IbIDg9OD05PBsgOR8aIBogGiAbAA0FAAAAAAAAAAAAAAAA",
    "stop": "JgAsABogGx8bHzs4Oj0cIBogNz4bHzkAC4MbHxsfGyA3Pjk7HCAaIDc9Gx85AA0FAAAAAAAAAAAAAAAA",
    "rewind": "JgAoABogODw5PDo9GSEaHzkgGT84AAuCGyA4Pjg9OD0bHxsfOSAZPTkADQU=",
    "fastforward": "JgAsABwgGh8bIDg9ODwcHxwfOD05HhwAC4IdHxogGx84PTg+Gx8bHzg9OR8cAA0FAAAAAAAAAAAAAAAA",
    "cd": "JgAkABwgNUA3PTk8Nz84Pjg9GwALZRsgNjw6Pjk7OT04Pjg9HAANBQAAAAA=",
    "radio": "JgAoAB0eGh8cHzk8OD04PTg9OSEZAAuDGx8cHx0eODw6PDg8OT04IBoADQU=",
    "pc": "JgAsABwgOD04PTg9GiEbHhwfGyE2PRoAC2YcIDg+OTs4PB0eGx8bIRogOTwZAA0FAAAAAAAAAAAAAAAA",
    "ipod": "JgAsADg9HR45PDg9OR4bIRsfGzwbHxsAC2Y4PhogOD04PTggGiAbIRo8GyEbAA0FAAAAAAAAAAAAAAAA",
    "tv": "JgAoADggGj05PDk9OSAZIBs9OCAbAAuAOiAcPDg+Nz82IRweGT83IBwADQU=",
    "av": "JgAoADk9HB84PTg8OSAaIBw7OD4ZAAtoNz0bIDg9OD02JBkgGz04OR4ADQU=",
    "hdd": "JgAoADggGz04PTc+OCAdHho+Gx44AAuEOR8aPTg+Nz42IhsgGT4aIDkADQU=",
    "aux": "JgAsABsfGSEcIDY+OD4aHzggGyAaPTkAC4IcHhwgGiA2QDVAGiA4HxshGT45AA0FAAAAAAAAAAAAAAAA",
}
